set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W5 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN U18 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports btn_u]
set_property PACKAGE_PIN T18 [get_ports btn_u]

set_property IOSTANDARD LVCMOS33 [get_ports btn_r]
set_property PACKAGE_PIN T17 [get_ports btn_r]

set_property IOSTANDARD LVCMOS33 [get_ports btn_d]
set_property PACKAGE_PIN U17 [get_ports btn_d]

set_property IOSTANDARD LVCMOS33 [get_ports btn_l]
set_property PACKAGE_PIN W19 [get_ports btn_l]

set_property PACKAGE_PIN V17 [get_ports {switch_0[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_0[0]}]
set_property PACKAGE_PIN V16 [get_ports {switch_0[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_0[1]}]
set_property PACKAGE_PIN W16 [get_ports {switch_0[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_0[2]}]
set_property PACKAGE_PIN W17 [get_ports {switch_0[3]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_0[3]}]

set_property PACKAGE_PIN V2 [get_ports {switch_1[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_1[0]}]
set_property PACKAGE_PIN T3 [get_ports {switch_1[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_1[1]}]
set_property PACKAGE_PIN T2 [get_ports {switch_1[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_1[2]}]
set_property PACKAGE_PIN R3 [get_ports {switch_1[3]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {switch_1[3]}]

set_property PACKAGE_PIN U2 [get_ports {anode[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]               
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property PACKAGE_PIN W4 [get_ports {anode[3]}]          
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]

set_property PACKAGE_PIN W7 [get_ports {outseg[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[0]}]
set_property PACKAGE_PIN W6 [get_ports {outseg[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[1]}]
set_property PACKAGE_PIN U8 [get_ports {outseg[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[2]}]
set_property PACKAGE_PIN V8 [get_ports {outseg[3]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[3]}]
set_property PACKAGE_PIN U5 [get_ports {outseg[4]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[4]}]
set_property PACKAGE_PIN V5 [get_ports {outseg[5]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[5]}]
set_property PACKAGE_PIN U7 [get_ports {outseg[6]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {outseg[6]}]

set_property PACKAGE_PIN U16 [get_ports {leds[0]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]                    
set_property IOSTANDARD LVCMOS33 [get_ports {leds[2]}]