# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/seg_decoder.xdc

# Block Designs: bd/seg_decoder/seg_decoder.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder || ORIG_REF_NAME==seg_decoder} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_clk_divider_0_0/seg_decoder_clk_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_clk_divider_0_0 || ORIG_REF_NAME==seg_decoder_clk_divider_0_0} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_Debouncer_0_0/seg_decoder_Debouncer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_Debouncer_0_0 || ORIG_REF_NAME==seg_decoder_Debouncer_0_0} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_decoder_0_0/seg_decoder_decoder_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_decoder_0_0 || ORIG_REF_NAME==seg_decoder_decoder_0_0} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_decoder_0_1/seg_decoder_decoder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_decoder_0_1 || ORIG_REF_NAME==seg_decoder_decoder_0_1} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_two_bit_counter_0_0/seg_decoder_two_bit_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_two_bit_counter_0_0 || ORIG_REF_NAME==seg_decoder_two_bit_counter_0_0} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_decoder_0_2/seg_decoder_decoder_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_decoder_0_2 || ORIG_REF_NAME==seg_decoder_decoder_0_2} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_decoder_0_3/seg_decoder_decoder_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_decoder_0_3 || ORIG_REF_NAME==seg_decoder_decoder_0_3} -quiet] -quiet

# IP: bd/seg_decoder/ip/seg_decoder_multiplexer_0_0/seg_decoder_multiplexer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==seg_decoder_multiplexer_0_0 || ORIG_REF_NAME==seg_decoder_multiplexer_0_0} -quiet] -quiet

# XDC: bd/seg_decoder/seg_decoder_ooc.xdc
